### ISSUE TITLE
Fix Chrome for Mac so Gotham font shows and right side aligns in header

### ISSUE THREAD

**Issue by mgdenman** [chrisbycz/Inside-RMS#3]

**Comment by chrisbycz** [comment]
Mimi,
I did a bit or research => http://blog.typekit.com/2014/02/04/chrome-bug-affecting-web-fonts/ 

What version of Chrome are you running on your Mac?

**Comment by mgdenman** [comment]
Unfortunately the latest version   Version 41.0.2272.89 (64-bit)



Mimi Garrity Denman
Director of Employee Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 3/11/15, 10:53 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Mimi,
I did a bit or research => http://blog.typekit.com/2014/02/04/chrome-bug-affecting-web-fonts/

What version of Chrome are you running on your Mac?

-

**Comment by chrisbycz** [comment]
When you inspect the HTML that is being rendered, what font does the code inspector say is being rendered?

**Comment by mgdenman** [comment]
This is the opening. Is that helpful?
<html dir="ltr" lang="en-US">
        <head id="ctl00_Head1"><meta http-equiv="X-UA-Compatible" content="IE=10" /><meta charset="utf-8" /><meta name="GENERATOR" content="Microsoft SharePoint" /><meta http-equiv="Content-type" content="text/html; charset=utf-8" /><meta http-equiv="Expires" content="0" />

        


        
        
        
        <link rel='shortcut icon' href='/_catalogs/masterpage/RMS/Common/Images/favicon.ico<http://insiderms/_catalogs/masterpage/RMS/Common/Images/favicon.ico>' type='image/vnd.microsoft.icon' /><link rel='shortcut icon' href='/_catalogs/masterpage/RMS/Common/Images/metrotile.png<http://insiderms/_catalogs/masterpage/RMS/Common/Images/metrotile.png>' TileColor='#0072C6' />

        
        <title>
        Inside RMS
        </title>

        
        <link id="CssRegistration1" rel="stylesheet" type="text/css" href="/Style%20Library/en-US/Themable/Core%20Styles/pagelayouts15.css<http://insiderms/Style%20Library/en-US/Themable/Core%20Styles/pagelayouts15.css>"/>
        <link id="CssRegistration1" rel="stylesheet" type="text/css" href="/_layouts/15/1033/styles/Themable/corev15.css?rev=5vnvqGmlkKiZE7lIH7ENng%3D%3D<http://insiderms/_layouts/15/1033/styles/Themable/corev15.css?rev=5vnvqGmlkKiZE7lIH7ENng%3D%3D>"/>
        <link rel="stylesheet" type="text/css" href="/Style%20Library/en-US/Themable/Core%20Styles/controls15.css<http://insiderms/Style%20Library/en-US/Themable/Core%20Styles/controls15.css>"/>
        <link id="MainCSS" rel="stylesheet" type="text/css" href="/Style%20Library/en-US/Themable/RMS_Main.css<http://insiderms/Style%20Library/en-US/Themable/RMS_Main.css>"/>
        <link id="SliderCSS" rel="stylesheet" type="text/css" href="/Style%20Library/en-US/Themable/jquery.bxslider.css<http://insiderms/Style%20Library/en-US/Themable/jquery.bxslider.css>"/>
        <link id="ScrollbarCSS" rel="stylesheet" type="text/css" href="/Style%20Library/en-US/Themable/RMS_Scrollbar.css<http://insiderms/Style%20Library/en-US/Themable/RMS_Scrollbar.css>"/>
        <link id="RMSHome2015CSS" rel="stylesheet" type="text/css" href="/Style%20Library/en-US/Themable/RMS_Home2015.css<http://insiderms/Style%20Library/en-US/Themable/RMS_Home2015.css>"/>



Mimi Garrity Denman
Director of Employee Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 3/11/15, 11:06 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


When you inspect the HTML that is being rendered, what font does the code inspector say is being rendered?

-

**Comment by chrisbycz** [comment]
Take a look at this quick video. It shows how to inspect an element on a web page to view its properties. 
https://www.dropbox.com/s/97obe77pndpofhf/InspectElementInChrome.gif?dl=0

**Comment by mgdenman** [comment]
I'm close but ...can you call me at my desk 510-505-3293


[cid:90A6868D-E3C5-46B9-BD9F-752F92130C31]
Mimi Garrity Denman
Director of Employee Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 3/11/15, 11:31 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Take a look at this quick video. It shows how to inspect an element on a web page to view its properties.
https://www.dropbox.com/s/97obe77pndpofhf/InspectElementInChrome.gif?dl=0

-

**Comment by chrisbycz** [comment]
Hi Mimi,
Can you please take a look at the Test environment?

I tried to force the font to the weather element.
http://insidermstst.rms.com/Pages/RMS_2015_Home.aspx

**Comment by mgdenman** [comment]
Font looks good - only small thing is not left aligned completely  in upper right

[cid:3789AFE0-C0AD-42E0-B192-32F89B0AFAAE]



Mimi Garrity Denman
Director of Employee Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 3/12/15, 1:28 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mimi,
Can you please take a look at the Test environment?

I tried to force the font to the weather element.
http://insidermstst.rms.com/Pages/RMS_2015_Home.aspx

-

**Comment by chrisbycz** [comment]
I'm glad the font is finally rendering for you. 

Can you please provide a screen shot of the alignment issue.

**Comment by mgdenman** [comment]
I sent you one but here it is again   maybe because I sent it to the other mailbox?

[cid:3F7A4705-23C3-4E03-9CF6-F3994FB1BF1D]





Mimi Garrity Denman
Director of Employee Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 3/12/15, 1:45 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm glad the font is finally rendering for you.

Can you please provide a screen shot of the alignment issue.

-
