### ISSUE TITLE
If possible global URL change 

### ISSUE THREAD

**Issue by mgdenman** [chrisbycz/Inside-RMS#5]
There are many, many pages and images and links (mostly the department pages) that are using the URL   This page is an example. http://intranet.rms.com/departments/ClientSupportServices/Pages/default.aspx  I changed the links on the images so they now show but the page has lost it’s formatting. And the header is not working properly. Luckily these pages are not linked right now. 

Rather than have to look at every page in the site, is it possible to globally change and link that starts with intranet.rms.com  to insiderms.com.  The IT department in another company I worked for did this – I know it’s possible – but not sure how. Something in the content and structure setting?

**Comment by chrisbycz** [comment]
Mimi,
Could you please share some history on where the intranet.rms domain came from? Has it always been an active domain? I checked the navigation on the Production site (http://insiderms.rms.com/) and couldnt find any explicit links to http://intranet.rms.com/. How are users navigating to this domain and pages that live on it? 

Thanks

**Comment by mgdenman** [comment]
Do you have the email I sent that gave examples- I'm a bit jammed right now but can find it if you can't find it



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/2/15, 10:57 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Mimi,
Could you please share some history on where the intranet.rms domain came from? Has it always been an active domain? I checked the navigation on the Production site (http://insiderms.rms.com/) and couldnt find any explicit links to http://intranet.rms.com/. How are users navigating to this domain and pages that live on it?

Thanks

-

**Comment by chrisbycz** [comment]
I'll take a look through my email.

**Comment by mgdenman** [comment]
Here's another example Chris- http://intranet.rms.com/departments/CloudOperations/Pages/default.aspx  The image in the carousel has intranet.rms.com.   I will ask Jay where that URL came from.
