### ISSUE TITLE
Create page template - date and ranking 

### ISSUE THREAD

**Issue by mgdenman** [chrisbycz/Inside-RMS#6]
Can we create a new page template that we will use for all pages to include a date (thinking upper right italic text, smaller than paragraph style) ranking (by stars) and a comment on this article box.  Not sure if this might be helpful  http://weblogs.asp.net/bsimser/adding-ratings-and-comments-to-sharepoint-publishing-pages

**Comment by chrisbycz** [comment]
/*
ADDED EMAIL CORRESPONDENCE TO COMMENTS.
NO ACTION REQUIRED.
*/

Correct.  You got it!

Thanks



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com

On 4/6/15, 10:29 AM, "Chris Byczkowski" <cbyczkowski@localwisdom.com> wrote:

Hi Mimi,
I did have a lovely weekend, thank you. I hope your weekend and Easter holiday was enjoyable as well. 

If I'm understanding you correctly, you're adding the Note Board web-part after a page is created created?

If so that's a slick move in the mean time! Kudos. 

The ultimate goal is still to have that functionality built into the page template so no additional web-parts need to be added. 

Thank you,
Christopher J. Byczkowski
Lead Web Curator
o: 609.269.2320 x223
e: cbyczkowski@localwisdom.com​

From: Mimi Denman <Mimi.Denman@rms.com>
Sent: Monday, April 06, 2015 11:31 AM
To: Chris Byczkowski
Subject: For what it is worth...for the new page template
 
Hi Chris,

Hope you had a nice weekend.

Not sure if this is helpful…but what I do now to add comments is use the Note Board web part and change the title to Comments.

Best,

Mimi 



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com

**Comment by mgdenman** [comment]
Cool!  Not rushing…really  :-)  do you have an ETA on the new page template?



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/6/15, 11:40 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


/*
ADDED EMAIL CORRESPONDENCE TO COMMENTS.
NO ACTION REQUIRED.
*/

Correct. You got it!

Thanks

Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/6/15, 10:29 AM, "Chris Byczkowski" cbyczkowski@localwisdom.com<mailto:cbyczkowski@localwisdom.com> wrote:

Hi Mimi,
I did have a lovely weekend, thank you. I hope your weekend and Easter holiday was enjoyable as well.

If I'm understanding you correctly, you're adding the Note Board web-part after a page is created created?

If so that's a slick move in the mean time! Kudos.

The ultimate goal is still to have that functionality built into the page template so no additional web-parts need to be added.

Thank you,
Christopher J. Byczkowski
Lead Web Curator
o: 609.269.2320 x223
e: cbyczkowski@localwisdom.com<mailto:cbyczkowski@localwisdom.com>​

From: Mimi Denman Mimi.Denman@rms.com<mailto:Mimi.Denman@rms.com>
Sent: Monday, April 06, 2015 11:31 AM
To: Chris Byczkowski
Subject: For what it is worth...for the new page template

Hi Chris,

Hope you had a nice weekend.

Not sure if this is helpful…but what I do now to add comments is use the Note Board web part and change the title to Comments.

Best,

Mimi

Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

**Comment by chrisbycz** [comment]
Hi Mimi,
I know this is a priority for you and the organization, I'm just trying to do as much information gathering as possible so we don't encounter any hiccups like we did during the first homepage deployment so I do apologize if this seems to be dragging out longer than expected. I just want to make sure we get this right the first time. 

After digesting the documentation and requirements you've provided, we can deliver an updated article page template for review by EOD this Wednesday the 8th.

**Comment by mgdenman** [comment]
Totally understand and I didn't think you were dragging it out. I'm just excited to make this change as is my new manager. Take the time you need. We can also have a quick conversation if you want just to make sure (please excuse the pun :-) on the same page



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/6/15, 12:25 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mimi,
I know this is a priority for you and the organization, I'm just trying to do as much information gathering as possible so we don't encounter any hiccups like we did during the first homepage deployment so I do apologize if this seems to be dragging out longer than expected. I just want to make sure we get this right the first time.

After digesting the documentation and requirements you've provided, we can deliver an updated article page template for review by EOD this Wednesday the 8th.

-

**Comment by chrisbycz** [comment]
I'm excited to work on these new features! 

I'll of course pick up the phone and give you a ring if I need to discuss in more detail than email can convey easily. 

I'll be working on this in the Test environment to avoid any disruptions to the live site. If you want to take a peak at the progress at any time all the work will be retroactive and visible on any of the article pages in the Test environment. This page for example =>  http://insidermstst.rms.com/Pages/Profile-P.Eidelman.aspx 

If you do decide to periodically check on the progress, I would like to recommend that feedback is withheld until after EOD Wednesday and consolidated so adjustments can be made in bulk as opposed to piece-meal. Will that work for you?

**Comment by mgdenman** [comment]
Promise- I'll wait for the "big reveal"   :-)



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/6/15, 1:02 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm excited to work on these new features!

I'll of course pick up the phone and give you a ring if I need to discuss in more detail than email can convey easily.

I'll be working on this in the Test environment to avoid any disruptions to the live site. If you want to take a peak at the progress at any time all the work will be retroactive and visible on any of the article pages in the Test environment. This page for example => http://insidermstst.rms.com/Pages/Profile-P.Eidelman.aspx

If you do decide to periodically check on the progress, I would like to recommend that feedback is withheld until after EOD Wednesday and consolidated so adjustments can be made in bulk as opposed to piece-meal. Will that work for you?

-

**Comment by chrisbycz** [comment]
:) hahah

**Comment by chrisbycz** [comment]
Hi Mimi,
We were able to deliver ahead of schedule. 

Attached is a marked up screenshot with a comment and question. 

You can also take a look at the following Test environment URL or any other article page as the new features are retroactive.
http://insidermstst.rms.com/Pages/Profile-P.Eidelman.aspx 


![rms_articlepageenhancements_4-7-2015](https://cloud.githubusercontent.com/assets/10729730/7029787/0700c168-dd2e-11e4-8568-d0ef87b257f1.jpg)

Looking forward to your feedback.

**Comment by chrisbycz** [comment]
Mimi,
Just updating this issues records based on our call.

1) I will be hiding the following section. 
![rms_tohide](https://cloud.githubusercontent.com/assets/10729730/7032883/d4dc4066-dd43-11e4-8785-ad8057dd5f7e.png)

2) Make the Article Dat field required
3) Make sure the date is right aligned on all browsers and devices. 

Please let me know if there is anything I've missed.

**Comment by mgdenman** [comment]
perfect



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/7/15, 1:34 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Mimi,
Just updating this issues records based on our call.

1) I will be hiding the following section.
[rms_tohide]<https://cloud.githubusercontent.com/assets/10729730/7032883/d4dc4066-dd43-11e4-8785-ad8057dd5f7e.png>

2) Make the Article Dat field required
3) Make sure the date is right aligned on all browsers and devices.

Please let me know if there is anything I've missed.

-

**Comment by chrisbycz** [comment]
Hi Mimi,
Can you please take a look at the following article page on the Test environment and let me know if the date is right aligned or not?

http://insidermstst.rms.com/Pages/RMS-at-the-DRR.aspx 

Additionally the default text under the comment field has been hidden and the Article Date column has been made required for the "Article Page" and "News Page" content types.

**Comment by mgdenman** [comment]
Looks great. One question - there seems to be a lot of space between the end of the article and the comments field. Is it possible to tighten that up?



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/8/15, 11:22 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mimi,
Can you please take a look at the following article page on the Test environment and let me know if the date is right aligned or not?

http://insidermstst.rms.com/Pages/RMS-at-the-DRR.aspx

Additionally the default text under the comment field has been hidden and the Article Date column has been made required for the "Article Page" and "News Page" content types.

-

**Comment by chrisbycz** [comment]
Let me take a look into that and see what can be done.

**Comment by chrisbycz** [comment]
Mimi,
looks like the extra space in that article was the result of a few additional hard carriage returns in the body of the post. 

I removed them.

Please take another look and let me know what you think.

http://insidermstst.rms.com/Pages/Profile-P.Eidelman.aspx

**Comment by mgdenman** [comment]
Perfect  In the words of Jean Luc Picard let's "Make it so"  :-)  if you are not a Star Trek fan you'll wonder what I'm talking about :-)

The ones where I added a note board field - that won't be removed will it?  We'll just have two...correct?





Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/8/15, 11:32 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Mimi,
looks like the extra space in that article was the result of a few additional hard carriage returns in the body of the post.

I removed them.

Please take another look and let me know what you think.

http://insidermstst.rms.com/Pages/Profile-P.Eidelman.aspx

-

**Comment by chrisbycz** [comment]
While I'm more of a James Tiberius Kirk fan you can rest assured I do appreciate the reference ;) 

If there are other posts with additional white space in the body of the article it will have to be removed manually. 

Could you please provide me with URLs for the two articles where the Note Board web-part was added?

**Comment by mgdenman** [comment]
There are many - I want to leave them though as there are nice comments. I don't mind that there are two fields...not the end of the world.



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/8/15, 11:41 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


While I'm more of a James Tiberius Kirk fan you can rest assured I do appreciate the reference ;)

If there are other posts with additional white space in the body of the article it will have to be removed manually.

Could you please provide me with URLs for the two articles where the Note Board web-part was added?

-

**Comment by chrisbycz** [comment]
Mimi,
I'm going to test the comment-email workflow by commenting on a article published by you in the Test environment. 

Please let me know if you receive an email by 9a.m. PST.

**Comment by mgdenman** [comment]
Will do



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 8:33 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Mimi,
I'm going to test the comment-email workflow by commenting on a article published by you in the Test environment.

Please let me know if you receive an email by 9a.m. PST.

-

**Comment by chrisbycz** [comment]
no email unless it went into spam...
REPLYREPLY ALLFORWARD
Mark as read
 
Mimi Denman <Mimi.Denman@rms.com>
Thu 4/9/2015 1:05 PM
Inbox
To:
Chris Byczkowski;

Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com

**Comment by chrisbycz** [comment]
Ok,
Thank you Mimi. I'm looking into the workflow process, if there is one. 

This is the article I commented on => http://insidermstst.rms.com/Pages/RMS_Functional-Org-3-19-15.aspx 

Is the email functionality required for launch? It wasn't in the original scope.

**Comment by mgdenman** [comment]
No it's not -  just a nice to have :-)



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 10:07 AM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok,
Thank you Mimi. I'm looking into the workflow process, if there is one.

This is the article I commented on => http://insidermstst.rms.com/Pages/RMS_Functional-Org-3-19-15.aspx

Is the email functionality required for launch? It wasn't in the original scope.

-

**Comment by chrisbycz** [comment]
Hi Mimi,
I just wanted to confirm a go live date for the updated page template.

Please let me know what decision has been made.

Thanks,

**Comment by mgdenman** [comment]
Yes you have a go.  Just want to confirm my previous question- if there are already notes on the page now there will just be two is that correct?



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 12:36 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mimi,
I just wanted to confirm a go live date for the updated page template.

Please let me know what decision has been made.

Thanks,

-

**Comment by chrisbycz** [comment]
That should be the result. I'm just looking for an example of an article with notes already in place for confirmation before I push the updates live

**Comment by mgdenman** [comment]
http://insiderms.rms.com/Pages/Leadership-profile-EYau.aspx   here's an example  We don't know why the man's picture is so large Dhiraj thought he fixed it - don't worry about that now



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 12:47 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


That should be the result. I'm just looking for an example of an article with notes already in place for confirmation before I push the updates live

-

**Comment by chrisbycz** [comment]
It's hard to confirm since that example isn't in the Test environment.

**Comment by chrisbycz** [comment]
I did some playing around in the Test environment. 

I added the note board web-part to the post below and assumptions are correct, there will just be 2. 
http://insidermstst.rms.com/Pages/Modeling-Mastery---Ingrid-Charvet-.aspx 

Since the note board web-part gets added to the content region of the page and the enhancements I've made are outside that area I believe they wont impact each other.

**Comment by mgdenman** [comment]
Great- let's do it.



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 1:00 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


I did some playing around in the Test environment.

I added the note board web-part to the post below and assumptions are correct, there will just be 2.
http://insidermstst.rms.com/Pages/Modeling-Mastery---Ingrid-Charvet-.aspx

Since the note board web-part gets added to the content region of the page and the enhancements I've made are outside that area I believe they wont impact each other.

-

**Comment by chrisbycz** [comment]
It shal be done. 

I'll let you know as soon as it's live.

**Comment by mgdenman** [comment]
Exciting!



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 1:07 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


It shal be done.

I'll let you know as soon as it's live.

-

**Comment by chrisbycz** [comment]
Mimi,
The new features have been implemented in Production. 

Below is a Production article link for validation. 
http://insiderms.rms.com/Pages/ISO_Re-Endorsement_04.15.aspx 

You will however notice the default comment text is displayed. If we hide this placeholder content via CSS it will effectively hide all comments as well which is unfortunate.

**Comment by mgdenman** [comment]
Ok - production environment?  Will it be live soon? I'm not sure of the process.



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 1:18 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Mimi,
The new features have been implemented in Production.

Below is a Production article link for validation.
http://insiderms.rms.com/Pages/ISO_Re-Endorsement_04.15.aspx

You will however notice the default comment text is displayed. If we hide this placeholder content via CSS it will effectively hide all comments as well which is unfortunate.

-

**Comment by chrisbycz** [comment]
My apologies. 

By "Production Environment" I mean it is live.

**Comment by mgdenman** [comment]
Nice job!



Mimi Garrity Denman
Director of Internal Communications
RMS
o: 510.505.3293
m: 650.208.4623
mimi.denman@rms.com<mailto:mimi.denman@rms.com>

On 4/9/15, 1:21 PM, "Christopher Byczkowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


My apologies.

By "Production Environment" I mean it is live.

-

**Comment by chrisbycz** [comment]
Thank you Mimi! :)

This was a cool project.
